### ISSUE TITLE
Any plans to port to .Net standard/core for OpenTK 4.0

### ISSUE THREAD

**Issue by danielscherzer** [opentk/ObjectTK#13]
Thansk for your very nice abstraction layer. 
After the release of OpenTK 4 are there any plans of porting your work to .Net standard/core?

**Comment by varon** [comment]
@danielscherzer  - Thanks for the input.

We're actually working on a total rewrite of this at the moment. Drop by the OpenTK Discord development channel for more info!

**Comment by danielscherzer** [comment]
Thanks for the info!
