### ISSUE TITLE
Shader compilation error

### ISSUE THREAD

**Issue by Polymaker** [opentk/ObjectTK#6]
When I try to compile the shaders from the included exemples I get an error telling me that the version directive must be first statement. 
I've looked at the code and it looks like some sort of line number reference is appended before anything and it seems to be the cause of the issue.

**Comment by JcBernack** [comment]
That is correct. The line references have to be added because shader sources may be stitched together from multiple files. Without them potential compilation error messages contain useless line information.
https://github.com/opentk/ObjectTK/blob/2bc61d30302d334f3e461750c2737ba37b03f3a0/ObjectTK/Shaders/ProgramFactory.cs#L141

What kind system are you running? Hardware, driver, etc.

**Comment by Polymaker** [comment]
My system is:
* CPU: Xeon E5-1630 v4
* OS: Windows 10 64 bits
* GPU: NVidia Quadro M2000 (driver version 23.21.13.9253)

I cloned the repo and tweaked the code to append the line reference after the version statement and it works but I have no clue if that would have some repercussions.

The system above is my work computer (lol) and I don't remember if I've tried on my personal PC.
I'll try that later.

**Comment by JcBernack** [comment]
If some compilers are so sensitive to the version statement, then I guess your solution is the only reasonable one 🤷‍♂

**Comment by Polymaker** [comment]
I tried on my personal computer (CPU: i7-7700K GPU: RTX 2070) and I encounter the same issue.
Could it be related to the fact that I updated the OpenTK references to the version 3.1.0?

**Comment by jvbsl** [comment]
No, it is driver related. GLSL specification says explicitely that #version needs to come first. If a compiler can do it without that being the case then the compiler doesn't follow the GLSL spec completely.
Of course in this case ObjectTK doesn't handle #version which it should.

**Comment by uzername** [comment]
I am having the same error. 
CPU: Intel i3 6100
GPU: Intel HD Graphics 530

Fixed that:
In `ObjectTK/ObjectTK/Shaders/ProgramFactory.cs`, in ` private static string GetShaderSource(string effectKey, List<Effect.Section> included = null)`

set lines:
```
//code here
                    // check if it is an include statement
                    const string includeKeyword = "#include";
                    const string versionKeyword = "#version";
                    if (!line.StartsWith(includeKeyword)&& !line.StartsWith(versionKeyword))
                    {
                        // add correct line number offset to the corresponding section within the effect file
                        if (fixLine)
                        {
                            source.AppendLine(string.Format("#line {0} {1}", lineNumber, fileNumber));
                            fixLine = false;
                        }
                        source.AppendLine(line);
                    }
//more code here
```

**Comment by varon** [comment]
Thanks to @uzername  - This should be closed!
