### ISSUE TITLE
Pass Data to Fragment Shader.

### ISSUE THREAD

**Issue by Donaut** [opentk/ObjectTK#9]
I'm new to OpenGL. I played with the examples and noticed that I can't send data directly to the fragment shaders instead of that I need to send to the vertex shader then the vertex shader sends it to the fragment shader. Is this normal?

**Comment by varon** [comment]
Yes.

**Comment by Donaut** [comment]
Thanks. https://stackoverflow.com/questions/58007053/how-to-pass-attributes-directly-to-the-fragment-shader-in-opengl
